// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package index

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.DataType, b.ko.Spec.DataType) {
		delta.Add("Spec.DataType", a.ko.Spec.DataType, b.ko.Spec.DataType)
	} else if a.ko.Spec.DataType != nil && b.ko.Spec.DataType != nil {
		if *a.ko.Spec.DataType != *b.ko.Spec.DataType {
			delta.Add("Spec.DataType", a.ko.Spec.DataType, b.ko.Spec.DataType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Dimension, b.ko.Spec.Dimension) {
		delta.Add("Spec.Dimension", a.ko.Spec.Dimension, b.ko.Spec.Dimension)
	} else if a.ko.Spec.Dimension != nil && b.ko.Spec.Dimension != nil {
		if *a.ko.Spec.Dimension != *b.ko.Spec.Dimension {
			delta.Add("Spec.Dimension", a.ko.Spec.Dimension, b.ko.Spec.Dimension)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DistanceMetric, b.ko.Spec.DistanceMetric) {
		delta.Add("Spec.DistanceMetric", a.ko.Spec.DistanceMetric, b.ko.Spec.DistanceMetric)
	} else if a.ko.Spec.DistanceMetric != nil && b.ko.Spec.DistanceMetric != nil {
		if *a.ko.Spec.DistanceMetric != *b.ko.Spec.DistanceMetric {
			delta.Add("Spec.DistanceMetric", a.ko.Spec.DistanceMetric, b.ko.Spec.DistanceMetric)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration) {
		delta.Add("Spec.EncryptionConfiguration", a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration)
	} else if a.ko.Spec.EncryptionConfiguration != nil && b.ko.Spec.EncryptionConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN) {
			delta.Add("Spec.EncryptionConfiguration.KMSKeyARN", a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN)
		} else if a.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil && b.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil {
			if *a.ko.Spec.EncryptionConfiguration.KMSKeyARN != *b.ko.Spec.EncryptionConfiguration.KMSKeyARN {
				delta.Add("Spec.EncryptionConfiguration.KMSKeyARN", a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.SSEType, b.ko.Spec.EncryptionConfiguration.SSEType) {
			delta.Add("Spec.EncryptionConfiguration.SSEType", a.ko.Spec.EncryptionConfiguration.SSEType, b.ko.Spec.EncryptionConfiguration.SSEType)
		} else if a.ko.Spec.EncryptionConfiguration.SSEType != nil && b.ko.Spec.EncryptionConfiguration.SSEType != nil {
			if *a.ko.Spec.EncryptionConfiguration.SSEType != *b.ko.Spec.EncryptionConfiguration.SSEType {
				delta.Add("Spec.EncryptionConfiguration.SSEType", a.ko.Spec.EncryptionConfiguration.SSEType, b.ko.Spec.EncryptionConfiguration.SSEType)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IndexName, b.ko.Spec.IndexName) {
		delta.Add("Spec.IndexName", a.ko.Spec.IndexName, b.ko.Spec.IndexName)
	} else if a.ko.Spec.IndexName != nil && b.ko.Spec.IndexName != nil {
		if *a.ko.Spec.IndexName != *b.ko.Spec.IndexName {
			delta.Add("Spec.IndexName", a.ko.Spec.IndexName, b.ko.Spec.IndexName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MetadataConfiguration, b.ko.Spec.MetadataConfiguration) {
		delta.Add("Spec.MetadataConfiguration", a.ko.Spec.MetadataConfiguration, b.ko.Spec.MetadataConfiguration)
	} else if a.ko.Spec.MetadataConfiguration != nil && b.ko.Spec.MetadataConfiguration != nil {
		if len(a.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys) != len(b.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys) {
			delta.Add("Spec.MetadataConfiguration.NonFilterableMetadataKeys", a.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys, b.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys)
		} else if len(a.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys, b.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys) {
				delta.Add("Spec.MetadataConfiguration.NonFilterableMetadataKeys", a.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys, b.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VectorBucketName, b.ko.Spec.VectorBucketName) {
		delta.Add("Spec.VectorBucketName", a.ko.Spec.VectorBucketName, b.ko.Spec.VectorBucketName)
	} else if a.ko.Spec.VectorBucketName != nil && b.ko.Spec.VectorBucketName != nil {
		if *a.ko.Spec.VectorBucketName != *b.ko.Spec.VectorBucketName {
			delta.Add("Spec.VectorBucketName", a.ko.Spec.VectorBucketName, b.ko.Spec.VectorBucketName)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.VectorBucketRef, b.ko.Spec.VectorBucketRef) {
		delta.Add("Spec.VectorBucketRef", a.ko.Spec.VectorBucketRef, b.ko.Spec.VectorBucketRef)
	}

	return delta
}
