// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package index

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/s3vectors"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/s3vectors/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/s3vectors-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Index{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetIndexOutput
	resp, err = rm.sdkapi.GetIndex(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetIndex", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "NotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Index.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.Index.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if resp.Index.DataType != "" {
		ko.Spec.DataType = aws.String(string(resp.Index.DataType))
	} else {
		ko.Spec.DataType = nil
	}
	if resp.Index.Dimension != nil {
		dimensionCopy := int64(*resp.Index.Dimension)
		ko.Spec.Dimension = &dimensionCopy
	} else {
		ko.Spec.Dimension = nil
	}
	if resp.Index.DistanceMetric != "" {
		ko.Spec.DistanceMetric = aws.String(string(resp.Index.DistanceMetric))
	} else {
		ko.Spec.DistanceMetric = nil
	}
	if resp.Index.EncryptionConfiguration != nil {
		f4 := &svcapitypes.EncryptionConfiguration{}
		if resp.Index.EncryptionConfiguration.KmsKeyArn != nil {
			f4.KMSKeyARN = resp.Index.EncryptionConfiguration.KmsKeyArn
		}
		if resp.Index.EncryptionConfiguration.SseType != "" {
			f4.SSEType = aws.String(string(resp.Index.EncryptionConfiguration.SseType))
		}
		ko.Spec.EncryptionConfiguration = f4
	} else {
		ko.Spec.EncryptionConfiguration = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Index.IndexArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Index.IndexArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Index.IndexName != nil {
		ko.Spec.IndexName = resp.Index.IndexName
	} else {
		ko.Spec.IndexName = nil
	}
	if resp.Index.MetadataConfiguration != nil {
		f7 := &svcapitypes.MetadataConfiguration{}
		if resp.Index.MetadataConfiguration.NonFilterableMetadataKeys != nil {
			f7.NonFilterableMetadataKeys = aws.StringSlice(resp.Index.MetadataConfiguration.NonFilterableMetadataKeys)
		}
		ko.Spec.MetadataConfiguration = f7
	} else {
		ko.Spec.MetadataConfiguration = nil
	}
	if resp.Index.VectorBucketName != nil {
		ko.Spec.VectorBucketName = resp.Index.VectorBucketName
	} else {
		ko.Spec.VectorBucketName = nil
	}

	rm.setStatusDefaults(ko)
	// GetIndex does not return resource tags. Fetch them via ListTagsForResource
	// so the delta against Spec.Tags is accurate and we avoid spurious deltas
	// (and the resulting reconcile loop).
	if err := rm.setResourceTags(ctx, ko); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return false
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetIndexInput, error) {
	res := &svcsdk.GetIndexInput{}

	if r.ko.Spec.IndexName != nil {
		res.IndexName = r.ko.Spec.IndexName
	}
	if r.ko.Spec.VectorBucketName != nil {
		res.VectorBucketName = r.ko.Spec.VectorBucketName
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateIndexOutput
	_ = resp
	resp, err = rm.sdkapi.CreateIndex(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateIndex", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.IndexArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.IndexArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateIndexInput, error) {
	res := &svcsdk.CreateIndexInput{}

	if r.ko.Spec.DataType != nil {
		res.DataType = svcsdktypes.DataType(*r.ko.Spec.DataType)
	}
	if r.ko.Spec.Dimension != nil {
		dimensionCopy0 := *r.ko.Spec.Dimension
		if dimensionCopy0 > math.MaxInt32 || dimensionCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field dimension is of type int32")
		}
		dimensionCopy := int32(dimensionCopy0)
		res.Dimension = &dimensionCopy
	}
	if r.ko.Spec.DistanceMetric != nil {
		res.DistanceMetric = svcsdktypes.DistanceMetric(*r.ko.Spec.DistanceMetric)
	}
	if r.ko.Spec.EncryptionConfiguration != nil {
		f3 := &svcsdktypes.EncryptionConfiguration{}
		if r.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil {
			f3.KmsKeyArn = r.ko.Spec.EncryptionConfiguration.KMSKeyARN
		}
		if r.ko.Spec.EncryptionConfiguration.SSEType != nil {
			f3.SseType = svcsdktypes.SseType(*r.ko.Spec.EncryptionConfiguration.SSEType)
		}
		res.EncryptionConfiguration = f3
	}
	if r.ko.Spec.IndexName != nil {
		res.IndexName = r.ko.Spec.IndexName
	}
	if r.ko.Spec.MetadataConfiguration != nil {
		f5 := &svcsdktypes.MetadataConfiguration{}
		if r.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys != nil {
			f5.NonFilterableMetadataKeys = aws.ToStringSlice(r.ko.Spec.MetadataConfiguration.NonFilterableMetadataKeys)
		}
		res.MetadataConfiguration = f5
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}
	if r.ko.Spec.VectorBucketName != nil {
		res.VectorBucketName = r.ko.Spec.VectorBucketName
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateIndex(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteIndexOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteIndex(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteIndex", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteIndexInput, error) {
	res := &svcsdk.DeleteIndexInput{}

	if r.ko.Spec.IndexName != nil {
		res.IndexName = r.ko.Spec.IndexName
	}
	if r.ko.Spec.VectorBucketName != nil {
		res.VectorBucketName = r.ko.Spec.VectorBucketName
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Index,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
