// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IndexSpec defines the desired state of Index.
//
// The attributes of a vector index.
type IndexSpec struct {

	// The data type of the vectors to be inserted into the vector index.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	DataType *string `json:"dataType"`
	// The dimensions of the vectors to be inserted into the vector index.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Dimension *int64 `json:"dimension"`
	// The distance metric to be used for similarity search.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	DistanceMetric *string `json:"distanceMetric"`
	// The encryption configuration for a vector index. By default, if you don't
	// specify, all new vectors in the vector index will use the encryption configuration
	// of the vector bucket.
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	// The name of the vector index to create.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	IndexName *string `json:"indexName"`
	// The metadata configuration for the vector index.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	MetadataConfiguration *MetadataConfiguration `json:"metadataConfiguration,omitempty"`
	// An array of user-defined tags that you would like to apply to the vector
	// index that you are creating. A tag is a key-value pair that you apply to
	// your resources. Tags can help you organize, track costs, and control access
	// to resources. For more information, see Tagging for cost allocation or attribute-based
	// access control (ABAC) (https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging.html).
	//
	// You must have the s3vectors:TagResource permission in addition to s3vectors:CreateIndex
	// permission to create a vector index with tags.
	Tags map[string]*string `json:"tags,omitempty"`
	// The name of the vector bucket to create the vector index in.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	VectorBucketName *string                                  `json:"vectorBucketName,omitempty"`
	VectorBucketRef  *ackv1alpha1.AWSResourceReferenceWrapper `json:"vectorBucketRef,omitempty"`
}

// IndexStatus defines the observed state of Index
type IndexStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Date and time when the vector index was created.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

// Index is the Schema for the Indices API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Index struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IndexSpec   `json:"spec,omitempty"`
	Status            IndexStatus `json:"status,omitempty"`
}

// IndexList contains a list of Index
// +kubebuilder:object:root=true
type IndexList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Index `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Index{}, &IndexList{})
}
