// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// The encryption configuration for a vector bucket or index. By default, if
// you don't specify, all new vectors in Amazon S3 vector buckets use server-side
// encryption with Amazon S3 managed keys (SSE-S3), specifically AES256. You
// can optionally override bucket level encryption settings, and set a specific
// encryption configuration for a vector index at the time of index creation.
type EncryptionConfiguration struct {
	KMSKeyARN *string `json:"kmsKeyARN,omitempty"`
	// Reference field for KMSKeyARN
	KMSKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsKeyRef,omitempty"`
	SSEType   *string                                  `json:"sseType,omitempty"`
}

// Summary information about a vector index.
type IndexSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	IndexARN         *string      `json:"indexARN,omitempty"`
	IndexName        *string      `json:"indexName,omitempty"`
	VectorBucketName *string      `json:"vectorBucketName,omitempty"`
}

// The attributes of a vector index.
type Index_SDK struct {
	CreationTime   *metav1.Time `json:"creationTime,omitempty"`
	DataType       *string      `json:"dataType,omitempty"`
	Dimension      *int64       `json:"dimension,omitempty"`
	DistanceMetric *string      `json:"distanceMetric,omitempty"`
	// The encryption configuration for a vector bucket or index. By default, if
	// you don't specify, all new vectors in Amazon S3 vector buckets use server-side
	// encryption with Amazon S3 managed keys (SSE-S3), specifically AES256. You
	// can optionally override bucket level encryption settings, and set a specific
	// encryption configuration for a vector index at the time of index creation.
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	IndexARN                *string                  `json:"indexARN,omitempty"`
	IndexName               *string                  `json:"indexName,omitempty"`
	// The metadata configuration for a vector index.
	MetadataConfiguration *MetadataConfiguration `json:"metadataConfiguration,omitempty"`
	VectorBucketName      *string                `json:"vectorBucketName,omitempty"`
}

// The metadata configuration for a vector index.
type MetadataConfiguration struct {
	NonFilterableMetadataKeys []*string `json:"nonFilterableMetadataKeys,omitempty"`
}

// Summary information about a vector bucket.
type VectorBucketSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	VectorBucketARN  *string      `json:"vectorBucketARN,omitempty"`
	VectorBucketName *string      `json:"vectorBucketName,omitempty"`
}

// The attributes of a vector bucket.
type VectorBucket_SDK struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The encryption configuration for a vector bucket or index. By default, if
	// you don't specify, all new vectors in Amazon S3 vector buckets use server-side
	// encryption with Amazon S3 managed keys (SSE-S3), specifically AES256. You
	// can optionally override bucket level encryption settings, and set a specific
	// encryption configuration for a vector index at the time of index creation.
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	VectorBucketARN         *string                  `json:"vectorBucketARN,omitempty"`
	VectorBucketName        *string                  `json:"vectorBucketName,omitempty"`
}
