// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VectorBucketSpec defines the desired state of VectorBucket.
//
// The attributes of a vector bucket.
type VectorBucketSpec struct {

	// The encryption configuration for the vector bucket. By default, if you don't
	// specify, all new vectors in Amazon S3 vector buckets use server-side encryption
	// with Amazon S3 managed keys (SSE-S3), specifically AES256.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	// The name of the vector bucket to create.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// An array of user-defined tags that you would like to apply to the vector
	// bucket that you are creating. A tag is a key-value pair that you apply to
	// your resources. Tags can help you organize and control access to resources.
	// For more information, see Tagging for cost allocation or attribute-based
	// access control (ABAC) (https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging.html).
	//
	// You must have the s3vectors:TagResource permission in addition to s3vectors:CreateVectorBucket
	// permission to create a vector bucket with tags.
	Tags map[string]*string `json:"tags,omitempty"`
}

// VectorBucketStatus defines the observed state of VectorBucket
type VectorBucketStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Date and time when the vector bucket was created.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

// VectorBucket is the Schema for the VectorBuckets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type VectorBucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VectorBucketSpec   `json:"spec,omitempty"`
	Status            VectorBucketStatus `json:"status,omitempty"`
}

// VectorBucketList contains a list of VectorBucket
// +kubebuilder:object:root=true
type VectorBucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VectorBucket `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VectorBucket{}, &VectorBucketList{})
}
